#include<iostream>
using namespace std;
#include<stdio.h>
#include<string.h>
int main()
{
    char A[31],B[31],C[31],D[31],E[31],F[31],G[31],H[31],I[31],J[31];
    gets(A);
    gets(B);
    gets(C);
    gets(D);
    gets(E);
    gets(F);
    gets(G);
    gets(H);
    gets(I);
    gets(J);
    int i,j,k;
    i=strlen(C);
    j=strlen(G);
    k=strlen(I);
    printf("%s\n",C);
    printf("%s\n",G);
    printf("%s\n",I);
    return 0;
}

